/* This file was automatically generated by CasADi 3.7.0+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dynamics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

#include <casadi/mem.h>

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {7, 25, 1};
static const casadi_int casadi_s1[3] = {3, 25, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* F:(X[7x25],U[3x25],dt)->(X_next[7x25]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  #error Code generation not supported for CallbackInternal
  return 0;
}

CASADI_SYMBOL_EXPORT int F(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int F_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int F_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int F_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void F_release(int mem) {
}

CASADI_SYMBOL_EXPORT void F_incref(void) {
}

CASADI_SYMBOL_EXPORT void F_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int F_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int F_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real F_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_in(casadi_int i) {
  switch (i) {
    case 0: return "X";
    case 1: return "U";
    case 2: return "dt";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* F_name_out(casadi_int i) {
  switch (i) {
    case 0: return "X_next";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* F_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int F_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int F_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* F_functions(void) {
  static casadi_functions fun = {
    F_incref,
    F_decref,
    F_checkout,
    F_release,
    F_default_in,
    F_n_in,
    F_n_out,
    F_name_in,
    F_name_out,
    F_sparsity_in,
    F_sparsity_out,
    F_work,
    F
  };
  return &fun;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
